<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="yzl-PC" name="Test" tests="361" failures="361" timestamp="7 Jul 2017 08:08:30 GMT" time="691.857" errors="0">
  <testcase name="detail001" time="3.281" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail001(MyTest.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail001 -->
  <testcase name="detail006" time="0.833" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail006(MyTest.java:104)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail006 -->
  <testcase name="detail007" time="0.837" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail007(MyTest.java:112)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail007 -->
  <testcase name="detail008" time="0.825" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail008(MyTest.java:120)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail008 -->
  <testcase name="detail009" time="0.83" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail009(MyTest.java:128)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail009 -->
  <testcase name="detail01" time="0.925" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail01(MyTest.java:87)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail01 -->
  <testcase name="detail010" time="0.834" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail010(MyTest.java:136)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail010 -->
  <testcase name="detail011" time="0.829" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail011(MyTest.java:144)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail011 -->
  <testcase name="detail012" time="0.842" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail012(MyTest.java:152)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail012 -->
  <testcase name="detail013" time="0.822" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail013(MyTest.java:160)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail013 -->
  <testcase name="detail014" time="0.93" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail014(MyTest.java:168)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail014 -->
  <testcase name="detail015" time="0.864" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail015(MyTest.java:176)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail015 -->
  <testcase name="detail016" time="0.825" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail016(MyTest.java:184)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail016 -->
  <testcase name="detail017" time="0.83" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail017(MyTest.java:192)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail017 -->
  <testcase name="detail018" time="0.812" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail018(MyTest.java:200)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail018 -->
  <testcase name="detail019" time="0.819" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail019(MyTest.java:208)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail019 -->
  <testcase name="detail020" time="0.782" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail020(MyTest.java:216)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail020 -->
  <testcase name="detail021" time="0.727" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail021(MyTest.java:224)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail021 -->
  <testcase name="detail022" time="0.779" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail022(MyTest.java:232)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail022 -->
  <testcase name="detail023" time="0.816" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail023(MyTest.java:240)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail023 -->
  <testcase name="detail024" time="0.816" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail024(MyTest.java:248)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail024 -->
  <testcase name="detail025" time="0.82" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail025(MyTest.java:256)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail025 -->
  <testcase name="detail026" time="0.812" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail026(MyTest.java:264)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail026 -->
  <testcase name="detail027" time="0.813" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail027(MyTest.java:272)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail027 -->
  <testcase name="detail028" time="0.77" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail028(MyTest.java:280)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail028 -->
  <testcase name="detail029" time="0.808" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail029(MyTest.java:288)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail029 -->
  <testcase name="detail030" time="0.812" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail030(MyTest.java:296)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail030 -->
  <testcase name="detail031" time="0.794" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail031(MyTest.java:304)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail031 -->
  <testcase name="detail032" time="0.81" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail032(MyTest.java:312)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail032 -->
  <testcase name="detail033" time="1.031" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail033(MyTest.java:320)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail033 -->
  <testcase name="detail034" time="1.084" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail034(MyTest.java:328)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail034 -->
  <testcase name="detail035" time="1.041" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail035(MyTest.java:336)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail035 -->
  <testcase name="detail036" time="1.032" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail036(MyTest.java:344)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail036 -->
  <testcase name="detail037" time="0.797" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail037(MyTest.java:352)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail037 -->
  <testcase name="detail038" time="0.81" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail038(MyTest.java:360)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail038 -->
  <testcase name="detail039" time="0.828" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail039(MyTest.java:368)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail039 -->
  <testcase name="detail040" time="0.827" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail040(MyTest.java:376)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail040 -->
  <testcase name="detail041" time="0.806" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail041(MyTest.java:384)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail041 -->
  <testcase name="detail042" time="0.814" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail042(MyTest.java:392)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail042 -->
  <testcase name="detail043" time="0.813" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail043(MyTest.java:400)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail043 -->
  <testcase name="detail044" time="0.811" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail044(MyTest.java:408)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail044 -->
  <testcase name="detail045" time="0.828" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail045(MyTest.java:416)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail045 -->
  <testcase name="detail046" time="0.82" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail046(MyTest.java:424)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail046 -->
  <testcase name="detail047" time="0.819" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail047(MyTest.java:432)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail047 -->
  <testcase name="detail048" time="0.705" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail048(MyTest.java:440)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail048 -->
  <testcase name="detail049" time="0.716" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail049(MyTest.java:448)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail049 -->
  <testcase name="detail050" time="0.719" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail050(MyTest.java:456)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail050 -->
  <testcase name="detail051" time="0.726" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail051(MyTest.java:464)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail051 -->
  <testcase name="detail052" time="0.716" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail052(MyTest.java:472)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail052 -->
  <testcase name="detail053" time="0.696" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail053(MyTest.java:480)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail053 -->
  <testcase name="detail054" time="0.729" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail054(MyTest.java:488)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail054 -->
  <testcase name="detail055" time="0.849" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail055(MyTest.java:496)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail055 -->
  <testcase name="detail056" time="0.784" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail056(MyTest.java:504)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail056 -->
  <testcase name="detail057" time="0.808" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail057(MyTest.java:512)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail057 -->
  <testcase name="detail058" time="0.828" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail058(MyTest.java:520)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail058 -->
  <testcase name="detail059" time="0.828" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail059(MyTest.java:528)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail059 -->
  <testcase name="detail060" time="0.823" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail060(MyTest.java:536)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail060 -->
  <testcase name="detail061" time="0.828" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail061(MyTest.java:544)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail061 -->
  <testcase name="detail062" time="0.813" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail062(MyTest.java:552)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail062 -->
  <testcase name="detail063" time="0.841" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail063(MyTest.java:560)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail063 -->
  <testcase name="detail064" time="0.827" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail064(MyTest.java:568)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail064 -->
  <testcase name="detail065" time="0.822" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail065(MyTest.java:576)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail065 -->
  <testcase name="detail066" time="0.81" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail066(MyTest.java:584)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail066 -->
  <testcase name="detail067" time="0.831" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail067(MyTest.java:592)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail067 -->
  <testcase name="detail068" time="0.816" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail068(MyTest.java:600)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail068 -->
  <testcase name="detail069" time="0.773" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail069(MyTest.java:608)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail069 -->
  <testcase name="detail070" time="0.831" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail070(MyTest.java:616)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail070 -->
  <testcase name="detail071" time="0.835" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail071(MyTest.java:624)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail071 -->
  <testcase name="detail072" time="0.825" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail072(MyTest.java:632)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail072 -->
  <testcase name="detail073" time="0.837" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail073(MyTest.java:640)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail073 -->
  <testcase name="detail074" time="0.811" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail074(MyTest.java:648)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail074 -->
  <testcase name="detail075" time="0.847" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail075(MyTest.java:656)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail075 -->
  <testcase name="detail076" time="0.827" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail076(MyTest.java:664)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail076 -->
  <testcase name="detail077" time="0.836" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail077(MyTest.java:672)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail077 -->
  <testcase name="detail078" time="0.822" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail078(MyTest.java:680)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail078 -->
  <testcase name="detail079" time="0.816" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail079(MyTest.java:688)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail079 -->
  <testcase name="detail080" time="0.804" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail080(MyTest.java:696)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail080 -->
  <testcase name="detail081" time="0.829" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail081(MyTest.java:704)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail081 -->
  <testcase name="detail082" time="0.84" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail082(MyTest.java:712)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail082 -->
  <testcase name="detail083" time="0.819" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail083(MyTest.java:720)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail083 -->
  <testcase name="detail084" time="0.818" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail084(MyTest.java:728)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail084 -->
  <testcase name="detail085" time="0.827" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail085(MyTest.java:736)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail085 -->
  <testcase name="detail086" time="0.819" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail086(MyTest.java:744)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail086 -->
  <testcase name="detail087" time="0.834" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail087(MyTest.java:752)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail087 -->
  <testcase name="detail088" time="0.816" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail088(MyTest.java:760)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail088 -->
  <testcase name="detail089" time="0.776" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail089(MyTest.java:768)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail089 -->
  <testcase name="detail090" time="0.773" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail090(MyTest.java:776)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail090 -->
  <testcase name="detail091" time="0.812" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail091(MyTest.java:784)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail091 -->
  <testcase name="detail092" time="0.808" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail092(MyTest.java:792)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail092 -->
  <testcase name="detail093" time="0.807" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail093(MyTest.java:800)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail093 -->
  <testcase name="detail094" time="0.804" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail094(MyTest.java:808)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail094 -->
  <testcase name="detail095" time="0.814" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail095(MyTest.java:816)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail095 -->
  <testcase name="detail096" time="0.901" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail096(MyTest.java:824)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail096 -->
  <testcase name="detail097" time="0.83" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail097(MyTest.java:832)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail097 -->
  <testcase name="detail098" time="0.809" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail098(MyTest.java:840)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail098 -->
  <testcase name="detail099" time="0.805" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail099(MyTest.java:848)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail099 -->
  <testcase name="detail100" time="0.803" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail100(MyTest.java:856)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail100 -->
  <testcase name="detail101" time="0.81" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail101(MyTest.java:864)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail101 -->
  <testcase name="detail102" time="0.809" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail102(MyTest.java:872)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail102 -->
  <testcase name="detail103" time="0.805" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail103(MyTest.java:880)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail103 -->
  <testcase name="detail104" time="0.855" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail104(MyTest.java:888)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail104 -->
  <testcase name="detail105" time="0.807" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail105(MyTest.java:896)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail105 -->
  <testcase name="detail106" time="0.811" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail106(MyTest.java:904)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail106 -->
  <testcase name="detail107" time="0.797" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail107(MyTest.java:912)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail107 -->
  <testcase name="detail108" time="0.801" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail108(MyTest.java:920)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail108 -->
  <testcase name="detail109" time="0.809" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail109(MyTest.java:928)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail109 -->
  <testcase name="detail110" time="0.819" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail110(MyTest.java:936)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail110 -->
  <testcase name="detail111" time="0.815" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail111(MyTest.java:944)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail111 -->
  <testcase name="detail112" time="0.778" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail112(MyTest.java:952)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail112 -->
  <testcase name="detail113" time="0.794" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail113(MyTest.java:960)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail113 -->
  <testcase name="detail114" time="0.804" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail114(MyTest.java:968)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail114 -->
  <testcase name="detail115" time="0.697" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail115(MyTest.java:976)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail115 -->
  <testcase name="detail116" time="0.771" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail116(MyTest.java:984)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail116 -->
  <testcase name="detail117" time="0.727" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail117(MyTest.java:992)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail117 -->
  <testcase name="detail118" time="0.787" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail118(MyTest.java:1000)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail118 -->
  <testcase name="detail119" time="1.026" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail119(MyTest.java:1008)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail119 -->
  <testcase name="detail120" time="1.007" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail120(MyTest.java:1016)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail120 -->
  <testcase name="detail121" time="1.014" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail121(MyTest.java:1024)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail121 -->
  <testcase name="detail122" time="1.036" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail122(MyTest.java:1032)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail122 -->
  <testcase name="detail123" time="0.801" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail123(MyTest.java:1040)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail123 -->
  <testcase name="detail124" time="0.811" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail124(MyTest.java:1048)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail124 -->
  <testcase name="detail125" time="0.81" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail125(MyTest.java:1056)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail125 -->
  <testcase name="detail126" time="0.823" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail126(MyTest.java:1064)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail126 -->
  <testcase name="detail127" time="0.806" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail127(MyTest.java:1072)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail127 -->
  <testcase name="detail128" time="0.825" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail128(MyTest.java:1080)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail128 -->
  <testcase name="detail129" time="0.751" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail129(MyTest.java:1088)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail129 -->
  <testcase name="detail130" time="0.799" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail130(MyTest.java:1096)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail130 -->
  <testcase name="detail131" time="0.813" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail131(MyTest.java:1104)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail131 -->
  <testcase name="detail132" time="0.805" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail132(MyTest.java:1112)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail132 -->
  <testcase name="detail133" time="0.817" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail133(MyTest.java:1120)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail133 -->
  <testcase name="detail134" time="0.82" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail134(MyTest.java:1128)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail134 -->
  <testcase name="detail135" time="0.854" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail135(MyTest.java:1136)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail135 -->
  <testcase name="detail136" time="0.878" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail136(MyTest.java:1144)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail136 -->
  <testcase name="detail137" time="0.887" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail137(MyTest.java:1152)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail137 -->
  <testcase name="detail138" time="0.827" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail138(MyTest.java:1160)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail138 -->
  <testcase name="detail139" time="0.904" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail139(MyTest.java:1168)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail139 -->
  <testcase name="detail140" time="0.921" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail140(MyTest.java:1176)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail140 -->
  <testcase name="detail141" time="1.053" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail141(MyTest.java:1184)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail141 -->
  <testcase name="detail142" time="1.015" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail142(MyTest.java:1192)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail142 -->
  <testcase name="detail143" time="1.005" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail143(MyTest.java:1200)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail143 -->
  <testcase name="detail144" time="1.012" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail144(MyTest.java:1208)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail144 -->
  <testcase name="detail145" time="0.818" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail145(MyTest.java:1216)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail145 -->
  <testcase name="detail146" time="0.83" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail146(MyTest.java:1224)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail146 -->
  <testcase name="detail147" time="0.816" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail147(MyTest.java:1232)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail147 -->
  <testcase name="detail148" time="0.802" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail148(MyTest.java:1240)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail148 -->
  <testcase name="detail149" time="0.823" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail149(MyTest.java:1248)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail149 -->
  <testcase name="detail150" time="1.448" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail150(MyTest.java:1256)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail150 -->
  <testcase name="detail151" time="1.022" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail151(MyTest.java:1264)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail151 -->
  <testcase name="detail152" time="1.022" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail152(MyTest.java:1272)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail152 -->
  <testcase name="detail153" time="1.022" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail153(MyTest.java:1280)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail153 -->
  <testcase name="detail154" time="0.811" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail154(MyTest.java:1288)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail154 -->
  <testcase name="detail155" time="0.812" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail155(MyTest.java:1296)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail155 -->
  <testcase name="detail156" time="0.838" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail156(MyTest.java:1304)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail156 -->
  <testcase name="detail157" time="0.81" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail157(MyTest.java:1312)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail157 -->
  <testcase name="detail158" time="0.815" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail158(MyTest.java:1320)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail158 -->
  <testcase name="detail159" time="0.822" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail159(MyTest.java:1328)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail159 -->
  <testcase name="detail160" time="0.826" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail160(MyTest.java:1336)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail160 -->
  <testcase name="detail161" time="0.823" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail161(MyTest.java:1344)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail161 -->
  <testcase name="detail162" time="0.832" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail162(MyTest.java:1352)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail162 -->
  <testcase name="detail163" time="0.784" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail163(MyTest.java:1360)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail163 -->
  <testcase name="detail164" time="0.824" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail164(MyTest.java:1368)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail164 -->
  <testcase name="detail165" time="0.812" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail165(MyTest.java:1376)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail165 -->
  <testcase name="detail166" time="0.732" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail166(MyTest.java:1384)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail166 -->
  <testcase name="detail167" time="0.776" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail167(MyTest.java:1392)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail167 -->
  <testcase name="detail168" time="0.713" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail168(MyTest.java:1400)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail168 -->
  <testcase name="detail169" time="0.742" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail169(MyTest.java:1408)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail169 -->
  <testcase name="detail170" time="0.809" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail170(MyTest.java:1416)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail170 -->
  <testcase name="detail171" time="0.816" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail171(MyTest.java:1424)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail171 -->
  <testcase name="detail172" time="0.811" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail172(MyTest.java:1432)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail172 -->
  <testcase name="detail173" time="0.802" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail173(MyTest.java:1440)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail173 -->
  <testcase name="detail174" time="0.811" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail174(MyTest.java:1448)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail174 -->
  <testcase name="detail175" time="0.814" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail175(MyTest.java:1456)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail175 -->
  <testcase name="detail176" time="0.884" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail176(MyTest.java:1464)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail176 -->
  <testcase name="detail177" time="1.05" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail177(MyTest.java:1472)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail177 -->
  <testcase name="detail178" time="1.022" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail178(MyTest.java:1480)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail178 -->
  <testcase name="detail179" time="1.609" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail179(MyTest.java:1488)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail179 -->
  <testcase name="detail180" time="1.599" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail180(MyTest.java:1496)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail180 -->
  <testcase name="detail181" time="0.821" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail181(MyTest.java:1504)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail181 -->
  <testcase name="detail182" time="1.221" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail182(MyTest.java:1512)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail182 -->
  <testcase name="detail183" time="0.825" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail183(MyTest.java:1520)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail183 -->
  <testcase name="detail184" time="2.159" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail184(MyTest.java:1528)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail184 -->
  <testcase name="detail185" time="1.016" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail185(MyTest.java:1536)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail185 -->
  <testcase name="detail186" time="1.037" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail186(MyTest.java:1544)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail186 -->
  <testcase name="detail187" time="1.033" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail187(MyTest.java:1552)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail187 -->
  <testcase name="detail188" time="0.833" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail188(MyTest.java:1560)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail188 -->
  <testcase name="detail189" time="0.84" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail189(MyTest.java:1568)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail189 -->
  <testcase name="detail190" time="0.844" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail190(MyTest.java:1576)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail190 -->
  <testcase name="detail191" time="0.826" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail191(MyTest.java:1584)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail191 -->
  <testcase name="detail192" time="0.819" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail192(MyTest.java:1592)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail192 -->
  <testcase name="detail193" time="0.829" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail193(MyTest.java:1600)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail193 -->
  <testcase name="detail194" time="0.846" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail194(MyTest.java:1608)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail194 -->
  <testcase name="detail195" time="0.825" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail195(MyTest.java:1616)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail195 -->
  <testcase name="detail196" time="0.849" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail196(MyTest.java:1624)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail196 -->
  <testcase name="detail197" time="0.837" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail197(MyTest.java:1632)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail197 -->
  <testcase name="detail198" time="0.805" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail198(MyTest.java:1640)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail198 -->
  <testcase name="detail199" time="0.799" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail199(MyTest.java:1648)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail199 -->
  <testcase name="detail200" time="1.726" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.detail200(MyTest.java:1656)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- detail200 -->
  <testcase name="list001" time="0.959" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list001(MyTest.java:1664)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list001 -->
  <testcase name="list002" time="1.035" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list002(MyTest.java:1672)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list002 -->
  <testcase name="list003" time="1.027" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list003(MyTest.java:1680)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list003 -->
  <testcase name="list004" time="0.885" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list004(MyTest.java:1688)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list004 -->
  <testcase name="list005" time="0.825" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list005(MyTest.java:1696)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list005 -->
  <testcase name="list006" time="0.837" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list006(MyTest.java:1704)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list006 -->
  <testcase name="list007" time="0.819" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list007(MyTest.java:1712)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list007 -->
  <testcase name="list008" time="0.81" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list008(MyTest.java:1720)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list008 -->
  <testcase name="list009" time="0.816" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list009(MyTest.java:1728)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list009 -->
  <testcase name="list010" time="0.805" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list010(MyTest.java:1736)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list010 -->
  <testcase name="list011" time="0.806" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list011(MyTest.java:1744)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list011 -->
  <testcase name="list012" time="0.83" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list012(MyTest.java:1752)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list012 -->
  <testcase name="list013" time="0.811" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list013(MyTest.java:1760)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list013 -->
  <testcase name="list014" time="0.827" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list014(MyTest.java:1768)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list014 -->
  <testcase name="list015" time="0.786" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list015(MyTest.java:1776)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list015 -->
  <testcase name="list016" time="0.731" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list016(MyTest.java:1784)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list016 -->
  <testcase name="list017" time="0.86" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list017(MyTest.java:1792)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list017 -->
  <testcase name="list018" time="0.844" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list018(MyTest.java:1800)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list018 -->
  <testcase name="list019" time="0.812" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list019(MyTest.java:1808)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list019 -->
  <testcase name="list020" time="0.821" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list020(MyTest.java:1816)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list020 -->
  <testcase name="list021" time="0.829" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list021(MyTest.java:1824)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list021 -->
  <testcase name="list022" time="0.84" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list022(MyTest.java:1832)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list022 -->
  <testcase name="list023" time="0.844" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list023(MyTest.java:1840)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list023 -->
  <testcase name="list024" time="0.874" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list024(MyTest.java:1848)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list024 -->
  <testcase name="list025" time="0.834" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list025(MyTest.java:1856)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list025 -->
  <testcase name="list026" time="0.827" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list026(MyTest.java:1864)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list026 -->
  <testcase name="list027" time="0.818" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list027(MyTest.java:1872)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list027 -->
  <testcase name="list028" time="0.807" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list028(MyTest.java:1880)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list028 -->
  <testcase name="list029" time="1.24" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list029(MyTest.java:1888)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list029 -->
  <testcase name="list030" time="1.039" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list030(MyTest.java:1896)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list030 -->
  <testcase name="list031" time="1.035" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list031(MyTest.java:1904)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list031 -->
  <testcase name="list032" time="1.012" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list032(MyTest.java:1912)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list032 -->
  <testcase name="list033" time="0.804" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list033(MyTest.java:1920)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list033 -->
  <testcase name="list034" time="0.818" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list034(MyTest.java:1928)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list034 -->
  <testcase name="list035" time="0.834" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list035(MyTest.java:1936)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list035 -->
  <testcase name="list036" time="0.753" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list036(MyTest.java:1944)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list036 -->
  <testcase name="list037" time="0.833" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list037(MyTest.java:1952)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list037 -->
  <testcase name="list038" time="0.814" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list038(MyTest.java:1960)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list038 -->
  <testcase name="list039" time="0.824" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list039(MyTest.java:1968)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list039 -->
  <testcase name="list040" time="0.806" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list040(MyTest.java:1976)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list040 -->
  <testcase name="list041" time="0.854" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list041(MyTest.java:1984)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list041 -->
  <testcase name="list042" time="0.84" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list042(MyTest.java:1992)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list042 -->
  <testcase name="list043" time="0.811" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list043(MyTest.java:2000)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list043 -->
  <testcase name="list044" time="0.829" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list044(MyTest.java:2008)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list044 -->
  <testcase name="list045" time="0.823" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list045(MyTest.java:2016)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list045 -->
  <testcase name="list046" time="0.818" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list046(MyTest.java:2024)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list046 -->
  <testcase name="list047" time="0.859" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list047(MyTest.java:2032)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list047 -->
  <testcase name="list048" time="0.816" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list048(MyTest.java:2040)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list048 -->
  <testcase name="list049" time="0.812" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list049(MyTest.java:2048)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list049 -->
  <testcase name="list050" time="0.818" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list050(MyTest.java:2056)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list050 -->
  <testcase name="list051" time="0.834" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list051(MyTest.java:2064)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list051 -->
  <testcase name="list052" time="0.819" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list052(MyTest.java:2072)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list052 -->
  <testcase name="list053" time="0.813" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list053(MyTest.java:2080)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list053 -->
  <testcase name="list054" time="0.801" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list054(MyTest.java:2088)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list054 -->
  <testcase name="list055" time="0.792" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list055(MyTest.java:2096)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list055 -->
  <testcase name="list056" time="0.811" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list056(MyTest.java:2104)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list056 -->
  <testcase name="list057" time="0.835" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list057(MyTest.java:2112)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list057 -->
  <testcase name="list058" time="0.804" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list058(MyTest.java:2120)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list058 -->
  <testcase name="list059" time="0.823" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list059(MyTest.java:2128)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list059 -->
  <testcase name="list060" time="0.81" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list060(MyTest.java:2136)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list060 -->
  <testcase name="list061" time="0.797" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list061(MyTest.java:2144)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list061 -->
  <testcase name="list062" time="0.807" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list062(MyTest.java:2152)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list062 -->
  <testcase name="list063" time="0.789" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list063(MyTest.java:2160)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list063 -->
  <testcase name="list064" time="0.79" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list064(MyTest.java:2168)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list064 -->
  <testcase name="list065" time="0.839" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list065(MyTest.java:2176)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list065 -->
  <testcase name="list066" time="0.83" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list066(MyTest.java:2184)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list066 -->
  <testcase name="list067" time="0.932" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list067(MyTest.java:2192)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list067 -->
  <testcase name="list068" time="0.837" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list068(MyTest.java:2200)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list068 -->
  <testcase name="list069" time="0.821" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list069(MyTest.java:2208)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list069 -->
  <testcase name="list070" time="1.045" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list070(MyTest.java:2216)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list070 -->
  <testcase name="list071" time="1.032" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list071(MyTest.java:2224)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list071 -->
  <testcase name="list072" time="1.013" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list072(MyTest.java:2232)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list072 -->
  <testcase name="list073" time="1.018" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list073(MyTest.java:2240)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list073 -->
  <testcase name="list074" time="0.793" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list074(MyTest.java:2248)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list074 -->
  <testcase name="list075" time="0.817" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list075(MyTest.java:2256)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list075 -->
  <testcase name="list076" time="0.813" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list076(MyTest.java:2264)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list076 -->
  <testcase name="list077" time="0.848" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list077(MyTest.java:2272)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list077 -->
  <testcase name="list078" time="0.816" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list078(MyTest.java:2280)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list078 -->
  <testcase name="list079" time="0.809" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list079(MyTest.java:2288)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list079 -->
  <testcase name="list080" time="0.806" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list080(MyTest.java:2296)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list080 -->
  <testcase name="list081" time="0.819" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list081(MyTest.java:2304)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list081 -->
  <testcase name="list082" time="0.832" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list082(MyTest.java:2312)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list082 -->
  <testcase name="list083" time="0.808" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list083(MyTest.java:2320)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list083 -->
  <testcase name="list084" time="0.816" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list084(MyTest.java:2328)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list084 -->
  <testcase name="list085" time="0.813" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list085(MyTest.java:2336)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list085 -->
  <testcase name="list086" time="0.811" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list086(MyTest.java:2344)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list086 -->
  <testcase name="list087" time="0.823" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list087(MyTest.java:2352)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list087 -->
  <testcase name="list088" time="0.812" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list088(MyTest.java:2360)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list088 -->
  <testcase name="list089" time="0.811" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list089(MyTest.java:2368)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list089 -->
  <testcase name="list090" time="0.83" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list090(MyTest.java:2376)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list090 -->
  <testcase name="list091" time="0.831" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list091(MyTest.java:2384)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list091 -->
  <testcase name="list092" time="0.843" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list092(MyTest.java:2392)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list092 -->
  <testcase name="list093" time="0.806" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list093(MyTest.java:2400)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list093 -->
  <testcase name="list094" time="0.827" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list094(MyTest.java:2408)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list094 -->
  <testcase name="list095" time="0.918" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list095(MyTest.java:2416)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list095 -->
  <testcase name="list096" time="0.809" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list096(MyTest.java:2424)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list096 -->
  <testcase name="list097" time="0.845" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list097(MyTest.java:2432)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list097 -->
  <testcase name="list098" time="0.826" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list098(MyTest.java:2440)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list098 -->
  <testcase name="list099" time="0.823" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list099(MyTest.java:2448)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list099 -->
  <testcase name="list100" time="0.81" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list100(MyTest.java:2456)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list100 -->
  <testcase name="list101" time="0.835" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list101(MyTest.java:2464)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list101 -->
  <testcase name="list102" time="0.939" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list102(MyTest.java:2472)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list102 -->
  <testcase name="list103" time="0.816" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list103(MyTest.java:2480)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list103 -->
  <testcase name="list104" time="3.847" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list104(MyTest.java:2488)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list104 -->
  <testcase name="list105" time="0.812" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list105(MyTest.java:2496)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list105 -->
  <testcase name="list106" time="0.804" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list106(MyTest.java:2504)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list106 -->
  <testcase name="list107" time="0.833" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list107(MyTest.java:2512)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list107 -->
  <testcase name="list108" time="0.83" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list108(MyTest.java:2520)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list108 -->
  <testcase name="list109" time="0.808" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list109(MyTest.java:2528)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list109 -->
  <testcase name="list110" time="0.818" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list110(MyTest.java:2536)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list110 -->
  <testcase name="list111" time="0.811" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list111(MyTest.java:2544)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list111 -->
  <testcase name="list112" time="0.828" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list112(MyTest.java:2552)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list112 -->
  <testcase name="list113" time="0.857" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list113(MyTest.java:2560)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list113 -->
  <testcase name="list114" time="0.931" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list114(MyTest.java:2568)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list114 -->
  <testcase name="list115" time="0.866" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list115(MyTest.java:2576)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list115 -->
  <testcase name="list116" time="0.81" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list116(MyTest.java:2584)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list116 -->
  <testcase name="list117" time="0.822" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list117(MyTest.java:2592)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list117 -->
  <testcase name="list118" time="0.812" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list118(MyTest.java:2600)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list118 -->
  <testcase name="list119" time="0.82" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list119(MyTest.java:2608)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list119 -->
  <testcase name="list120" time="0.806" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list120(MyTest.java:2616)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list120 -->
  <testcase name="list121" time="0.808" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list121(MyTest.java:2624)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list121 -->
  <testcase name="list122" time="0.812" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list122(MyTest.java:2632)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list122 -->
  <testcase name="list123" time="0.823" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list123(MyTest.java:2640)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list123 -->
  <testcase name="list124" time="0.824" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list124(MyTest.java:2648)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list124 -->
  <testcase name="list125" time="0.814" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list125(MyTest.java:2656)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list125 -->
  <testcase name="list126" time="0.81" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list126(MyTest.java:2664)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list126 -->
  <testcase name="list127" time="0.819" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list127(MyTest.java:2672)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list127 -->
  <testcase name="list128" time="0.76" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list128(MyTest.java:2680)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list128 -->
  <testcase name="list129" time="0.784" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list129(MyTest.java:2688)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list129 -->
  <testcase name="list130" time="0.807" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list130(MyTest.java:2696)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list130 -->
  <testcase name="list131" time="0.787" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list131(MyTest.java:2704)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list131 -->
  <testcase name="list132" time="0.789" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list132(MyTest.java:2712)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list132 -->
  <testcase name="list133" time="0.812" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list133(MyTest.java:2720)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list133 -->
  <testcase name="list134" time="0.805" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list134(MyTest.java:2728)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list134 -->
  <testcase name="list135" time="0.8" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list135(MyTest.java:2736)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list135 -->
  <testcase name="list136" time="0.804" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list136(MyTest.java:2744)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list136 -->
  <testcase name="list137" time="0.815" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list137(MyTest.java:2752)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list137 -->
  <testcase name="list138" time="0.8" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list138(MyTest.java:2760)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list138 -->
  <testcase name="list139" time="0.804" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list139(MyTest.java:2768)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list139 -->
  <testcase name="list140" time="0.81" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list140(MyTest.java:2776)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list140 -->
  <testcase name="list141" time="0.832" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list141(MyTest.java:2784)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list141 -->
  <testcase name="list142" time="0.807" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list142(MyTest.java:2792)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list142 -->
  <testcase name="list143" time="0.833" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list143(MyTest.java:2800)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list143 -->
  <testcase name="list144" time="0.813" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list144(MyTest.java:2808)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list144 -->
  <testcase name="list145" time="0.805" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list145(MyTest.java:2816)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list145 -->
  <testcase name="list146" time="0.802" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list146(MyTest.java:2824)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list146 -->
  <testcase name="list147" time="0.807" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list147(MyTest.java:2832)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list147 -->
  <testcase name="list148" time="0.854" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list148(MyTest.java:2840)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list148 -->
  <testcase name="list149" time="0.811" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list149(MyTest.java:2848)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list149 -->
  <testcase name="list150" time="0.801" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list150(MyTest.java:2856)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list150 -->
  <testcase name="list151" time="0.801" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list151(MyTest.java:2864)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list151 -->
  <testcase name="list152" time="0.804" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list152(MyTest.java:2872)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list152 -->
  <testcase name="list153" time="0.842" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list153(MyTest.java:2880)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list153 -->
  <testcase name="list154" time="0.833" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list154(MyTest.java:2888)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list154 -->
  <testcase name="list155" time="0.824" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.list155(MyTest.java:2896)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- list155 -->
  <testcase name="search0010" time="0.046" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.search0010(MyTest.java:71)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- search0010 -->
  <testcase name="search0011" time="0.737" classname="com.test.testcase.MyTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.test.testcase.MyTest.search0011(MyTest.java:78)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- search0011 -->
  <testcase name="search003" time="0.087" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.search003(MyTest.java:15)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- search003 -->
  <testcase name="search004" time="190.018" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.search004(MyTest.java:23)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- search004 -->
  <testcase name="search005" time="189.783" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.search005(MyTest.java:31)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- search005 -->
  <testcase name="search006" time="0.291" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.search006(MyTest.java:39)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- search006 -->
  <testcase name="search007" time="0.258" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.search007(MyTest.java:47)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- search007 -->
  <testcase name="search008" time="0.82" classname="com.test.testcase.MyTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.test.testcase.MyTest.search008(MyTest.java:54)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- search008 -->
  <testcase name="search009" time="4.732" classname="com.test.testcase.MyTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [null]
	at com.test.testcase.MyTest.search009(MyTest.java:63)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- search009 -->
</testsuite> <!-- Test -->
